### PR TITLE
slider instance collection

### PR DESCRIPTION
**Pull request by Xirdion**
I have added a js variable to store the different swiper instances.
So it is possible to add events to the slider after it was created.

In my case I like to add a function to the `slideChange` swiper-event.
Now it is possible to get the slider in another javascript file and add the custom function to the instance.
```javascript
swiperSliders['swiperID'].on('slideChange', function() {});
```

### CODE REVIEW

**Comment by fritzmg** [comment]
Yeah, I have thought about this recently actually. I would prefer a different approach though. I think it would be better, if the `initSwiper` function simply returns the swiper instance. Thus, if you need control over the swiper, anyone can then adjust their `ce_swiperStop.html5` template to something like this:
```php

    </div>
    <?php if ($this->sliderPagination): ?>
      <div class="swiper-pagination"></div>
    <?php endif; ?>
    <?php if ($this->sliderButtons): ?>
      <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div>
    <?php endif; ?>
  </div>

  <script>
    (function() {
      var swiper = initSwiper({
        id: '<?= $this->sliderId ?>',
        wrapperClass: '<?= $this->wrapperClass ?>',
        params: <?= json_encode($this->parameters) ?>
      });
      <?php if ('mySliderId' === $this->sliderId): ?>
        swiper.on('slideChange', function() { … });
      <?php endif; ?>
    });
  </script>

</div>
```
And you can still add it to a global swiper collection as well, if you want. What do you think?

**Comment by Xirdion** [comment]
Ah this is also a nice approach. Then I would prefer yours because there you have the config at the slider.

**Comment by fritzmg** [comment]
Ok, then all we need to change right now is
```diff
-        new Swiper(swiperContainer, params);
+        return new Swiper(swiperContainer, params);
```
:)

May be we could also introduce a `swiper_default` template (with the same data), so that the JavaScript and wrapper stop template are split up and you only need to override the `swiper_default` template then.

**Comment by Xirdion** [comment]
So I updated the javascript files to return the swiper instance.

**Comment by fritzmg** [comment]
thx, released as `3.3.1`

**Comment by Xirdion** [comment]
thx :)

**Pull request merged**
